### PR TITLE
fix: Remove hard code socket control path

### PR DESCRIPTION
**Pull request by jneo8**
Remove the hard core `/var/run/openvswitch/`
Right now it will be replaced by `Client.System.RunDir`

### CODE REVIEW

**Comment by jneo8** [comment]
Hi @greenpau, Can I also get review on this one?

**Comment by greenpau** [comment]
@jneo8 , how did you test it? Unfortunately i did not set up ci/cd for this repo and will unlikely do it.

**Comment by jneo8** [comment]
I test it manually on my environment which has customized ovs path.
I didn't test it manually on the normal ovs environment. Consider this PR replace the hard code with the default SystemDir variable, I guess it should be fine. Unless there is possible that `ctl` will be not under `System.Rundir`.

**Comment by jneo8** [comment]
Hi @greenpau, any more information you need?

**Comment by jneo8** [comment]
Hello @greenpau, any feedback or thing you want us to implement?

**Comment by greenpau** [comment]
@jneo8 will look at it today.

**Comment by jneo8** [comment]
Create new PR: #8

**Pull request closed without merging**
