### PR TITLE
fix: Remove hard code socket control path

### PR DESCRIPTION
**Pull request by jneo8**
Remove the hard code `/var/run/openvswitch/`
Right now it will be replaced by `Client.System.RunDir`

### CODE REVIEW

**Comment by greenpau** [comment]
@jneo8 , is this one ready?

**Comment by jneo8** [comment]
Yes, it's ready. The purpose of this PR just make `updateRefs` function to avoid the hard code issue.

**Comment by greenpau** [comment]
@jneo8 , I switched to using Rocky Linux.

Installed Open vSwitch in the following way.

```bash
dnf install centos-release-nfv-openvswitch
dnf list "openvswitch*" "ovn*"
dnf -y install openvswitch3.1
dnf -y install ovn22.12 ovn22.12-central
systemctl status openvswitch
systemctl start ovn-northd
```

Will add OVN to the mix to test your PR.

**Review by greenpau — APPROVED** [review]

**Comment by greenpau** [comment]
@jneo8 , thank you for contributing! 👍

**Pull request merged**
